# Generated by Django 4.1.3 on 2023-04-01 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App',
            new_name='DemoApp',
        ),
    ]
