# Generated by Django 4.1.3 on 2023-05-01 09:44

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio2', '0002_remove_demoapp_img_url_demoapp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoapp',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default.png', force_format='WEBP', keep_meta=True, quality=100, scale=1, size=[500, 700], upload_to='portfolio2/app_images/'),
        ),
    ]
