# Generated by Django 4.1.3 on 2023-04-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio2', '0002_rename_app_demoapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demoapp',
            name='img',
        ),
        migrations.AddField(
            model_name='demoapp',
            name='img_url',
            field=models.CharField(default='media/portfolio2/app_images/<django.db.models.fields.CharField>', max_length=200),
        ),
    ]
