# Generated by Django 4.1.3 on 2023-04-18 19:23

from django.db import migrations
import portfolio2.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio2', '0002_rename_app_demoapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demoapp',
            name='img',
            field=portfolio2.helpers.ResizedImageField(default='portfolio2/app_images/default.webp', upload_to='portfolio2/app_images'),
        ),
    ]
