# Generated by Django 4.1.3 on 2023-04-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='ParisTargetDate',
        ),
    ]
