# Generated by Django 4.1.3 on 2022-12-02 23:14
# pylint: skip-file

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile2',
        ),
    ]
