# Generated by Django 4.1.3 on 2022-11-17 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=99)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jean Dupont', max_length=30)),
                ('email', models.EmailField(default='jean.dupont@gmail.com', max_length=254)),
                ('mobile', models.CharField(default='07 69 92 92 92', max_length=15)),
                ('address', models.CharField(default="Saint Cyr L'Ecole, Paris", max_length=99)),
                ('photo', models.ImageField(default='commerce_app/profile_photos/default.png', upload_to='profile_photos')),
                ('role', models.CharField(choices=[('client', 'CLIENT ROLE'), ('vendor', 'VENDOR ROLE')], default='client', max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default="Men's Shirt", max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('photo', models.ImageField(upload_to='product_photos')),
                ('color', models.CharField(default='black', max_length=20)),
                ('size', models.CharField(choices=[('small', 'Size Small'), ('medium', 'Size Medium'), ('large', 'Size Large'), ('x-LARGE', 'Size X-Large')], default='medium', max_length=10)),
                ('quantity', models.IntegerField(default=50)),
                ('gender', models.CharField(choices=[('men', 'menwear'), ('women', 'womenwear')], default='men', max_length=10)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_cart_quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
